name: Release Build
on:
  release:
    types:
      - published
jobs:
  build:
    name: Build and Attach Release Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            architecture: x64
            runtime: win-x64
            suffix: win-x64
          - os: windows-latest
            architecture: x86
            runtime: win-x86
            suffix: win-x86
          - os: ubuntu-latest
            architecture: x64
            runtime: linux-x64
            suffix: linux-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore dependencies
        run: dotnet restore src/UnrealLocresEditor.Desktop
      
      - name: Generate version.txt
        run: echo "${{ github.event.release.tag_name }}" > ./src/UnrealLocresEditor.Desktop/version.txt
      
      - name: Build
        run: dotnet publish src/UnrealLocresEditor.Desktop --runtime ${{ matrix.runtime }} -c Release --output ./output/${{ matrix.runtime }}
      
      - name: Create artifacts directory
        run: mkdir -p artifacts
      
      - name: Create ZIP Archive
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            powershell -Command "Compress-Archive -Path ./output/${{ matrix.runtime }}/* -DestinationPath ./artifacts/UnrealLocresEditor-${{ github.event.release.tag_name }}-${{ matrix.suffix }}.zip"
          else
            cd output/${{ matrix.runtime }} && zip -r ../../artifacts/UnrealLocresEditor-${{ github.event.release.tag_name }}-${{ matrix.suffix }}.zip ./*
          fi
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.suffix }}
          path: artifacts/UnrealLocresEditor-${{ github.event.release.tag_name }}-${{ matrix.suffix }}.zip

  attach-assets:
    name: Attach Build Artifacts to Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
